version: '3.8'
services:
  user_db:
    image: "postgres:17.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - user-data:/var/lib/postgres/data
  activemq:
    image: 'apache/activemq-classic:6.1.4'
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      - ACTIVEMQ_CONNECTION_USER=admin
      - ACTIVEMQ_CONNECTION_PASSWORD=password
volumes:
  user-data: