apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  labels:
    app: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      name: user-app
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app-container
          image: born2flex/user-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_URL
              value: jdbc:postgresql://user-db-service:5432/user_db
            - name: DATASOURCE_USERNAME
              value: postgres
            - name: DATASOURCE_PASSWORD
              value: password
            - name: ACTIVEMQ_URL
              value: tcp://user-mq-service:61616
            - name: ACTIVEMQ_USER
              value: admin
            - name: ACTIVEMQ_PASSWORD
              value: password
      restartPolicy: Always
