apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mq
  template:
    metadata:
      labels:
        app: user-mq
    spec:
      containers:
        - name: activemq
          image: apache/activemq-classic:5.18.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 61616
            - containerPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: user-mq-service
spec:
  ports:
    - name: tcp
      port: 61616
      targetPort: 61616
    - name: web-ui
      port: 8161
      targetPort: 8161
  selector:
    app: user-mq
