spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  activemq:
    broker-url: tcp://localhost:61616
  security:
    user:
      name:
      password:
user:
  queue: user-queue
project:
  version: '@project.version@'
  security:
    permit-all: /auth/**, /swagger-ui/**, /v3/api-docs/**
domain:
  back: ${BACK_URI:http://localhost:8080}
