name: Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test --file user-service/pom.xml
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: 'https://sonarcloud.io/'
          continue-on-error: 'true'

      - name: CheckStyle Linter
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.CHECKSTYLE_TOKEN }}
          reporter: github-pr-review
#          level: warning
          checkstyle_config: checkstyle.xml

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
          token: ${{ secrets.CHECKSTYLE_TOKEN }}
          pass-emoji: ✔️
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          update-comment: 'true'
          title: 'JaCoCo Report'
          continue-on-error: 'true'
